### ISSUE TITLE
[Question] How do you generate pkg using brighterscript on this project?

### ISSUE THREAD

**Issue by priscila225** [iBicha/playlet#109]
I want to know how you generate a pkg signed using brighterscript of this project. I tried creating a private channel just for test purposes, but I got error 400. I was trying using the traditional roku deploy command and this one too from tools https://github.com/iBicha/playlet/blob/main/tools/sign-package.js

**Comment by iBicha** [comment]
Good question! I'll explain how how I release Playlet.

First, get familiar with [Packaging Roku channels](https://developer.roku.com/en-ca/docs/developer-program/publishing/packaging-channels.md#new-key-generation)

So this means you need a "signing password" to get a signed package.

Once that's done, you need to add it to the `.env` file. I described the [env file here](https://github.com/iBicha/playlet/tree/main/docs#setting-up-visual-studio-code). But there's also the signing password needed to go into that file. My `.env` file looks like this (these are not real values):
```
ROKU_DEV_TARGET=192.168.1.13
ROKU_DEVPASSWORD=123abc
ROKU_SIGN_PASSWORD=VNhJWwRzVt2YWhrV1RVTN1kyRQ==
ROKU_DEV_ID=e688cad1f417466daf0ae20726b5fcfc72874e6f
```

Once I have that in place, I primarily use two commands for building:
```
npm run build:release:ci
```
This command does all the steps except signing the package. It's what being used for the [automated releases](https://github.com/iBicha/playlet/releases/tag/unstable) 

```
npm run build:release
```
This command does `build:release:ci` + sign the package. It's literally `npm run build:release:ci && npm run sign-package`
If you only want to run the sign package step, use `npm run sign-package`.

I also have a process that I follow whenever I release a new version [documented here](https://github.com/iBicha/playlet/blob/main/docs/RELEASING.md)

**Comment by priscila225** [comment]
Thank you so much for your input on this one. This helped me a lot!
