### ISSUE TITLE
Error playing video

### ISSUE THREAD

**Issue by WizardOfWor1969** [iBicha/playlet#127]
I run an invidious server local on my network, I am running invidious (Current version: 2023.08.07-34508966 @ master)
I am running Playlet Version 0.10.0 , Playlet Library Version 0.10.3

Connecting to Invidious on my web browsers , everything plays and works fine. But with Playlet, I get no previews and trying to play videos with , I get an Error playing video popup. (See screenshots)

![signal-2023-08-07-160010_002](https://github.com/iBicha/playlet/assets/52321250/6aa8582c-c1a1-4206-9f6b-c78004f85d2d)
![signal-2023-08-07-160010_003](https://github.com/iBicha/playlet/assets/52321250/77649d82-4c06-4812-b773-ff6ce197ff03)

**Comment by iBicha** [comment]
Feels like a deja-vu, isn't this the same error as #78 ?

**Comment by WizardOfWor1969** [comment]
Yes, it was. Thanks for setting me straight.
