### ISSUE TITLE
Enhancement request - handle URL with timestamp.

### ISSUE THREAD

**Issue by Xytrios** [iBicha/playlet#149]
Hi @iBicha 

First of all thank you for your amazing work. 

I noticed that the search bar doesn't currently search results when searching a URL that includes a timestamp (Ex: "https://youtu.be/ZzkAQitaUv4?t=718")

In order for the "app"/web client to provide results, one must first remove the string parameters "?t=718" which then provides results for the URL "https://youtu.be/ZzkAQitaUv4"

Thank you.
Cheers

**Comment by iBicha** [comment]
Thanks for the suggestion!

Although I understand the why (wanting to share the link for Youtube and then paste it in the search to find and cast it) I have mixed feelings about modifying the search query. After all, sometimes it might be intended to search for something that has `t=718` in it. 

Another possibility is to allow the web app to read the clipboard. That way, when you copy a link and open the web app, the link would be detected and and the cast dialog will show up. Although this would require the clipboard permission, and it is not supported on all browsers.

Will need to think about this more

**Comment by iBicha** [comment]
Ok I think I've implemented a solution to this, without messing with the search.
When you have a link to a video in the clipboard, simply hit `Ctrl+v` anywhere in the page. If on mobile, long press in the search text field, and hit paste.
This will cause the app to detect the url and show the dialog to cast the video, including the timestamp. No need to use the search of the url.
The fix implemented in the [canary build](https://github.com/iBicha/playlet/releases/tag/canary), and will be available in the next release.
