### ISSUE TITLE
Make Popular Feed Optional

### ISSUE THREAD

**Issue by ReExpert** [iBicha/playlet#160]
Invidious allows disabling the "popular" feed at the instance level. This is useful for those who run private instances and don't want browsing history to be available to the rest of the small group.
See: https://github.com/iv-org/invidious/issues/4128

When disabled, the invidious player in web browser shows "The Popular feed has been disabled by the administrator."
Currently, PlayLet shows an error message pop up that it can't load a feed every time the home screen is loaded.

A better option would be to either silently replace the popular feed with a message that it's been disabled or have a configuration option to not show the feed. Or both.

**Comment by iBicha** [comment]
Thanks for the request, that makes sense to me (I did not know you can disable popular)

I think if we get a 400 from the server, it is safe to say an endpoint is disabled and we should not be pinging it. So this sounds like it can be done by silently removing "Popular" from the list if the server does not want us to see it.

I do have bigger plans for customizing the feed pages, but I feel like handling this case specifically is faster for now.
