### ISSUE TITLE
Enhancement request selecting Up in fullscreen video mode opens player controls

### ISSUE THREAD

**Issue by disc7** [iBicha/playlet#170]
Would be great if selecting Up in fullscreen video mode opens player controls. At the moment to open video player controls in fullscreen mode requires toggling pause/play, or seeking via left/right arrows, rewind/ff or replay button.

**Comment by iBicha** [comment]
> Would be great if selecting Up in fullscreen video mode opens player controls. At the moment to open video player controls in fullscreen mode requires toggling pause/play, or seeking via left/right arrows, rewind/ff or replay button.

Thanks for the suggestion. The default UI provided by Roku (from the [Video](https://developer.roku.com/en-ca/docs/references/scenegraph/media-playback-nodes/video.md#ui-fields) node) does not provide a way to programmatically pull up the UI controls (I don't one anyway).

So the only way to do this is to recreate all the UI and handle this case manually. I do have plans to do that, but it will have to wait a bit.

For what it is worth, if the goal is just to show the title, then the OK button would do that.
