### ISSUE TITLE
Videos from a specific channel playing in random languages. Not able to set language in the options. 

### ISSUE THREAD

**Issue by FlareHeart** [iBicha/playlet#171]
There is a channel I watch called Diary of a CEO and the videos from that channel seem to be playing in random languages. Some play in Spanish, some play in English, and some play in French. I have tried both the "always" and "never" options for the invidious proxy thinking that it may have been something to do with region in invidious, but that has not helped. Is there a way we can set a language to prevent it playing videos in other languages when available? I will put specific examples below. 

This one plays in Spanish - https://www.youtube.com/watch?v=PACpvHgJ9HM

This one plays in French - https://www.youtube.com/watch?v=vwFxptz77II

This one plays in English - https://www.youtube.com/watch?v=L7zWT3l3DV0

**Comment by iBicha** [comment]
Thanks for reporting the issue. Fortunately this has been fixed recently, and is available in the latest [Canary Release](https://github.com/iBicha/playlet/releases/tag/canary)

This has to do with how we manage videos with multiple audio tracks with different languages. the fix consists of detecting all languages and selecting the right default one.

With the fix applied, the right track should be selected, and alternative languages should be available in the menu as well:

1. Press Options (*) and select `Accessibility and language`
<img src="https://github.com/iBicha/playlet/assets/17722782/663431c6-7678-4ff8-9a81-2d0c8e92f128" width="400" />

2. Select Audio Track
<img src="https://github.com/iBicha/playlet/assets/17722782/f0610ec7-86f1-4260-ab85-9383659d894f" width="400" />

3. If there are multiple languages, you should see them in the list.
<img src="https://github.com/iBicha/playlet/assets/17722782/de747ed0-fde5-43ad-b27a-608b186e342d" width="400" />

The fix will be available in the next release. If you need to use this fix/feature right now, you can use the Canary release.

PS: A Canary release is basically the next version that has not been released to everyone yet. It might contain more features, but also it has not been thoroughly tested and might not be considered stable.

**Comment by FlareHeart** [comment]
Fantastic, thanks! I'll give the canary build a try.

**Comment by iBicha** [comment]
Great, closing this issue
