### ISSUE TITLE
[Bug] Channel video count is always zero in search

### ISSUE THREAD

**Issue by apainintheneck** [iBicha/playlet#173]
Hello,

I just started using this app a few days ago and I'm really enjoying the experience compared to the default YouTube app. I did notice one small bug though. The channel video count seems to always be zero in search even for big channels with hundreds of videos.

![Screen Shot 2023-10-21 at 12 15 35 PM](https://github.com/iBicha/playlet/assets/42982186/eb983c93-9aac-4717-9a7b-8e7a6fcb8193)

![Screen Shot 2023-10-21 at 12 14 47 PM](https://github.com/iBicha/playlet/assets/42982186/65bf6485-e724-49b0-8052-15aff79b3ec7)

**Comment by iBicha** [comment]
Thanks for reporting the issue.

This is related to https://github.com/iv-org/invidious/issues/4105, which basically boils down to Youtube and how they used to return the video count of channel in the search, but they don't do that anymore.

This has been recently fixed on Invidious, and now it shows the Channel handle.

Before:
<img width="294" alt="Screen Shot 2023-10-21 at 3 50 08 PM" src="https://github.com/iBicha/playlet/assets/17722782/551acc07-d7a4-4011-bfe8-6f04966a34eb">

After:
<img width="296" alt="Screen Shot 2023-10-21 at 3 50 40 PM" src="https://github.com/iBicha/playlet/assets/17722782/17e63e29-3650-4f2f-a7d5-76ef4c64c21e">

So I guess Playlet needs to use the channel handle as well.

**Comment by iBicha** [comment]
Fixed - it is now available in the [Canary release](https://github.com/iBicha/playlet/releases/tag/canary), and will be available in the next release.

**Comment by apainintheneck** [comment]
That makes sense. Thanks!
