### ISSUE TITLE
Feature request: Please make the Home Screen customizable 

### ISSUE THREAD

**Issue by WizardOfWor1969** [iBicha/playlet#182]
Would like to be able to turn off or on what is currently on the Home Screen at a minimum.

**Comment by iBicha** [comment]
Thanks for opening the issue. I understand this is related to https://github.com/iBicha/playlet/issues/51#issuecomment-1666954847, I haven't ignored that. The bookmarks is a stopgap towards that, but I've been making plans towards the UI and decomposition of the screens. Here's the current plan:

### Search
As it is in its current form.

### Explore
- Trending
- Trending - Music
- Trending - Gaming
- Trending - Movies
- Popular

### Me
- Continue watching
- Subscriptions
- Playlists
- Watch History

### Bookmarks
Whatever bookmarks exists here

Finally, I do intend to make each screen optional and can be toggled from the settings, as we as each row in them.

=======

Now back to the current Bookmarks feature, it's now possible to bookmark Subscriptions and Playlists from the home screen, with whatever other items you want, and you will not need to use the home screen at all.

**Comment by WizardOfWor1969** [comment]
I am not sure ,but can it be set via whatever the user has already selected for Invidious home page? Is that available to you?

**Comment by iBicha** [comment]
> I am not sure ,but can it be set via whatever the user has already selected for Invidious home page? Is that available to you?

Available, yes. Playlet's presentation is different from Invidious. Invidious shows one feed at a time, while Playlet shows many things at once. 
Nonetheless, I'm prototyping a kind of "editor" that allows you to disable certain feeds, and change their order as well #250 .
That should be about enough to remove anything you don't care about

**Comment by iBicha** [comment]
#250 merged, with the ability to disable feeds and reorder them. That should be enough for now to allow some level of customization.
We will refine the UI layout in later features
