### ISSUE TITLE
[enhancement] Disable and Clear search history

### ISSUE THREAD

**Issue by gorshco** [iBicha/playlet#191]
I'd like to request the addition of two basic functionalities as the title suggests;

1. The ability to disable search history ("Don't save search history"). This would probably reside in the settings menu.
2. The ability to clear the existing search history. This can probably reside in the settings menu, or maybe as a "button" under the recent searches.

Love the project!

**Comment by iBicha** [comment]
Thanks for the feedback!
Disabling search history makes sense, I'll add that to the settings.
Just so you know, there's already a button to clear the search history in the settings. Was the setting not clear?

**Comment by gorshco** [comment]
Just found it, I initially didn't scroll all the way to the bottom.
So yeah, a toggle to disable search history in that section would be appreciated!
