### ISSUE TITLE
Can't sign in

### ISSUE THREAD

**Issue by PikaGamer8** [iBicha/playlet#204]
Hey, y'all, just found this app via Reddit. I am trying to sign in using the QR code to the invidious instance inv.tux.pizza but Everytime I scan the QR code or type in the URL manually, the page won't load and end up giving me an error. I tried and got this error on both Firefox and Chrome. Is this a Playlet issue or something else? Thanks for the help in advance.

P.S I also tried with every other default Invidious instance as well.!

[Screenshot_20231114_222256_Firefox.jpg](https://github.com/iBicha/playlet/assets/77557847/ad469096-1577-428b-b136-4e1e7c49c081)

**Comment by iBicha** [comment]
Thanks for reporting, This is strange.

When I try with `inv.tux.pizza`, the signup page shows up as expected.

- Is both the phone and the TV on the same wifi/network?
- Do you have some setup that you think might cause this? (like a VPN for example)
- Are able to open the web app? (link to `http://192.168.1.x:8888/` as opposed to http://192.168.1.x:8888/invidious/login)
- Are you able to access app logs? (`http://192.168.1.x:8888/logs/app_logs.txt` - maybe not, but doesn't hurt to try)

**Comment by iBicha** [comment]
@PikaGamer8 following up - is this issue still happening?

**Comment by PikaGamer8** [comment]
Sorry I wasn't able to comment I am moving homes right now. I am not home right now but once I get home, I'll make sure to follow up.

**Comment by PikaGamer8** [comment]
Sorry for the late responses but it turns out it was a problem with my ISP blocking the URL for some reason so I switched ISP to Verizon and it worked.

**Comment by iBicha** [comment]
Thank you for the follow up, glad it's working again

**Comment by SudoVanilla** [comment]
I'm getting this issue.

**Comment by SudoVanilla** [comment]
Nevermind, restarting the whole TV worked.
