### ISSUE TITLE
Roku app store version not being updated

### ISSUE THREAD

**Issue by tomkel** [iBicha/playlet#206]
It's still on v0.10.0

**Comment by iBicha** [comment]
Thanks for creating the issue.

About Playlet version: as it says version 0.10.0, it is totally fine. You should also see the Playlet Library version, which is 0.17.0 as of right now.

The differences are:
- Playlet app version (0.10.0) is the app submitted to the Roku store. It is basically a "loader" of the actual app
- Playlet lib version (0.17.0) is what contains the actual app logic, and gets released through Github.
This mechanism allows me to release new versions immediately through Github, without going through the Roku store, which can take days. Playlet app is therefore released less often, as it doesn't change frequently.

I hope this clarifies things.
