### ISSUE TITLE
Error with BrightScript

### ISSUE THREAD

**Issue by TheBossMan3** [iBicha/playlet#215]
It says there is a problem with the dot operator or something

**Comment by TheBossMan3** [comment]
Subscriptions do not work on Playlet and it shows this error

**Comment by iBicha** [comment]
Thanks for reporting this, I've identified the issue and now it is fixed.
It was caused by a regression in a brighterscript version, which broke things on the Canary build.
I have reverted to a previously working version until the root cause is identified.
Thanks!
