### ISSUE TITLE
Lower resolution viewing options

### ISSUE THREAD

**Issue by joshuabengal** [iBicha/playlet#216]
I see only Auto and 720p as a selectable playback options. It would be helpful to add lower options like 480p and 360p and 240p for the bandwidth conscious among us.

**Comment by iBicha** [comment]
Hey, thanks for the suggestion. I would like to have this supported as well (in fact already in the roadmap in #6 - `Quality selector`)
Just to expand on why you would want lower resolutions if you don't mind me asking, do you have some limitations that makes you want to use less bandwidth? (like metered connection, or you want to keep bandwidth on TV low so it does not disrupt other networking?) just curious.

**Comment by joshuabengal** [comment]
In my particular case, my primary issue is I suffer from a visual disability and one of it's effects is severe eye strain headaches when viewing video at to high resolution. I need to downgrade videos to 480p or lower to make them watchable. I can only watch SD TV channels, I run my streaming stick through HDMI -> Composite cable converters, etc. 

However I know there are folks on none cable or fiber internet connections like satellite or mobile home internet and conserving bandwidth would be a big feature for them, and I usually try to come up with reasons for enhancements that would apply to a broader base of folks vs just me and my situation. I stumbled across this app cause YouTube updated their app and upped the color saturation on it's video player for some reason and now it is unwatchable without triggering my migraines, so I am hoping I can get this working as an alternative if a lower res video option was available. I also need to learn how Invidious works and how to get my subs and stuff to work with it.

**Comment by iBicha** [comment]
Thanks for the context, that's really interesting.
I'll will look into adding some kind of setting to set more quality selectors (or perhaps a filter of resolutions you don't want)

**Comment by joshuabengal** [comment]
Awesome. I think just some additional options below 720p would be fine. I have to use 480p, people on mobile internet may want to go even lower.

**Comment by iBicha** [comment]
I have added a "Medium" quality setting. For most videos this will be 360p. (but could be 480p? I'm actually not sure.)
The reason for this is Youtube serves two types for video streams:
- Streams where the video audio are in separate files: This way the device can adapt based on internet speed. Usually contain all available qualities.
- Streams where the video audio are in the same file: designed to play as is. Usually these are 720p, 360p and 144p
With that in mind, when the "Medium" quality is selected, we will check if we have a 360p or 480p in the non-adaptive formats, and if found, we'll play that. If not it falls back to the default.

This feature is now available in Canary build, and will be available in the next version.

**Comment by TheBossMan3** [comment]
Could you add higher resolution options for people with 4k TVs and stuff because we have really good bandwidth but Playlet plays 4K video at 480p half the time

**Comment by iBicha** [comment]
@TheBossMan3 I intend to make the full range of qualities available in a selector. I only added the medium quality option for the accessibility issue mentioned by @joshuabengal, and because the approach was fast to implement.
That being said, the Auto option should start with lower res version, but kick up to 1080p if the video allows it and the internet speed is good.

For 4K, it have tinkered with things for a while but I still haven't figured out the ideal setup for things to work.
Roku's [Streaming specifications](https://developer.roku.com/en-ca/docs/specs/media/streaming-specifications.md) have very specific format, container and codecs in order for 4k to work, and they do not match exactly the streams I'm getting from Invidious. I need to take time to dig into this even further in order to understand how to support 4k/60FPS/HDR properly.

On my 4k TV, opening a 4k video usually plays at 1080p. Not great, but it's currently not that bad.

**Comment by TheBossMan3** [comment]
4k HDR has worked sometimes in auto mode

**Comment by xa4hf8** [comment]
> **do you have some limitations that makes you want to use less bandwidth?**

> **I have to use 480p, people on mobile internet may want to go even lower.**

Trucks, boats and recreational vehicles are frequently equipped with a TV and router that employs a cellular or satellite connection.  Many cellular networks also offer some kind of fixed wireless service to residential properties through a partner or subsidiary (if not directly).  All of them have a hard or soft data cap of some sort.

Most of the people on metered connections do not want to blow their data cap by watching podcasts & radio shows on high (or medium) resolution.  I think the best solution there is to support lower resolutions as the default in Settings, along with a manual control that can be accessed easily during playback, to increase resolution temporarily for the selected object.  In some situations, some users would even prefer to discard the video component of the stream and render audio only.
