### ISSUE TITLE
Feature Request: filter to hide YouTube Shorts

### ISSUE THREAD

**Issue by merlinstardust** [iBicha/playlet#219]
I would love to see a filter to hide YouTube Shorts from subscriptions.

I have a lot of subscriptions and these days, every time I look at the subscriptions video list, I see one long video and then a dozen shorts. It makes it really hard to find any long form content that I actually want to watch.

So having a filter or section that excludes shorts would be great.

(If you point me to the right section in the code, I may be able to help build this. I've done web dev for years but never a Roku app so I don't know how difficult it is)

**Comment by iBicha** [comment]
Hey, thanks for suggesting this, and for offering to help!
In fact this is a popular request, and I agree with it, I would disable shorts myself, but not as simple to do.
It seems there isn't a simple way to differentiate between a short and a regular video.
I will close this ticket as duplicate for now, but feel free to check the discussions in #81 , #211 and https://github.com/iv-org/invidious/issues/2585
