### ISSUE TITLE
Add subtitles to video playback 

### ISSUE THREAD

**Issue by EmeraldRalts** [iBicha/playlet#225]
As it stands I don't believe that subtitles are supported, it would be massively appreciated if subtitle support could be added (even if it just pulls from youtube's auto-subtitles.)

**Comment by iBicha** [comment]
Thank you for opening the issue. Subtitles are supported, but there's a little "gotcha" to know about.
On popular Invidious instances with a lot of traffic, Youtube sees a lot of traffic coming from one computer and thinks it is a bot, so it blocks subtitles on it.

What you can do is, go to the settings, Invidious preferences, and change the instance. You can find many public instances, or select a custom one if you have one.

Also, to make sure the instance you select is not currently blocked, you can use the `Test instance` button which will run multiple tests to make sure Playlet can communicate with the server. Just make sure the `Fetch video captions` test is passing.

Once that done, you should be able to see captions/subtitles if you have them enabled on your Roku.

If this is not the issue, please let me know, and we will dig into it.

**Comment by iBicha** [comment]
@EmeraldRalts did this solve the issue?

**Comment by iBicha** [comment]
I will close this issue for now, as I do not expect issues with subtitles, apart from what I mentioned in popular Invidious instances.
Feel free to bring this up again if there's another issue with subtitles
