### ISSUE TITLE
Search not working from web app on iOS Safari

### ISSUE THREAD

**Issue by iBicha** [iBicha/playlet#227]
Reported on reddit, search not working on iOS Safari ([link](https://www.reddit.com/r/youtube/comments/18kpgcl/comment/kdukbts/?utm_source=share&utm_medium=web2x&context=3))

**Comment by TheBossMan3** [comment]
It works perfectly for me

**Comment by iBicha** [comment]
> It works perfectly for me

Thanks for confirming, this is good news.
I will increase the compatibility of the web app with older devices in case this is the issue, otherwise, without specifics from this user on reddit, I wouldn't be able to do more. 
Will reopen if there's a way to reproduce the issue for specific devices.

**Comment by iBicha** [comment]
Reported on iOS 17.1.2
