### ISSUE TITLE
Oitv

### ISSUE THREAD

**Issue by GabydaSilvaLima** [iBicha/playlet#242]
#EXTM3U
 
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjqatl2ESFA896A6qq3Sx6mOk7HoETOS31l0f-FpUyV9jY-riw0J5TH6kUxEicIiSyPcG0HGNbQzSCi50THW4b5q4VQwJVlNXKZX5GilSAvharuETWvycIRr9UC5I385yMoTJmJ5toi9CMSLgjGvvgMNtMn1I_0ehFgtINDIgPPuU7vA-DOq-9BjdatSDHA/s738/images%20(2).jpeg" goup-title="",TV/CANAL "", Adult Swim
https://tvembed.net/swim/index.m3u8?token=120e16131c5b01b10a62e477304930bfe8e62b52-e10a339df1c0076f962b69d6abc3b25b-1703681162-1703673962&remote=45.5.202.18
#EXTM3U
 
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiF7Vi3MBvb4tiudwKzPjpC2DpZDYZuwGZjaLRH9iEK4B9Kb3V0djY5u0HU7S4k33F8on1vOsLSvC66bPmqr3mcj7xUy3Wgu6bvw5PUijHPCDV3uGe6WjVxmvx_aiMNbG804lcSDEgY-12YNeJT2ehkJXl-kf3ztUI16fg_3GNOS1RyO2J7Y1ctRc4BVM7A/s866/disney-channel5093.jpg" goup-title="",TV/CANAL "", Disney Channel 
https://tvembed.net/disney/index.m3u8?token=116306c545b7dc14d7b63d5646e051821b1e0ce7-0ec83425da0ee546fd8b6b2ee757aa0e-1703681378-1703674178&remote=45.5.202.18
#EXTM3U
 
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiSyhyphenhyphengAPUNNUzypzYqaJGWzJvuEVjGRUyMg5YQxPCfnZOn5ThB8CgXqBGavneR3C3uYTpF-zQEmEs7eSGVseoXHsOTM-IyJf2mpXZ3OqQuy5qCr6RX460F7CUWK3qfT44xAbAZykmPg8QFkJarLJATPZLoj7fkZnHqfd_a-o7SQfgCtjh64ixurFn_HGdf/s512/anime-2.png" goup-title="",TV/CANAL "", canal otaku HD
https://stmv1.srvif.com/otaku/otaku/playlist.m3u8

#EXTM3U
 
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjAIxZG8LDxx_KnfWPWgXOkld5f45jVr8cZkmEU6Aa20h5r61rxGBe8Tyvz8g9t_Zl1ZRRO1htwYYuxehOxV0vJFoEZ4vEDmHqPy2pN7lBVC9x4Ymftx84O2-krF0wR4XWJMlurxmqWzeyfrMwX-RRF3jz4xUsPWLCSRDuD4vZI4cepkLB9scap6QHT7mzM/s639/images%20(1).jpeg" goup-title="",TV/CANAL "", Gloob FULL HD
https://tvembed.net/gloob/index.m3u8?token=347ac9b1347e8d1e6ae19552b7375e24e01b9f12-cfed4cff033f5551374d65f043eda76d-1703681548-1703674348&remote=45.5.202.18

#EXTM3U
 
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEiLokdb7Sfx7PEQ0IFN2LbZDvm2rXB_s-GECYxgm5AIdd_-CRHXQhcS63Y4sKU75bRzIrP3ZAGG5h45AkB3cdxlLfG36Mjqbx25fZW2teOZzaWLJ3bRSLZPy4bPK5o0K-lJgpVjkZorUdvU9-lnW5vYUuGG46-wnu39WbjGyd6jryMr9QptikHv-UYIg80U/s1280/Nickelodeon_2023_logo_(outline).svg.png" goup-title="",TV/CANAL "", Nick HD
https://tvembed.net/nick/index.m3u8?token=58b1438bb81077a8c4188f77e5216b61b133b49d-e489f3ccb9162040daef50493a02e5ff-1703682834-1703675634&remote=45.5.202.18

#EXTM3U
 
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEj21uJoLQFIJR6FNR4HgHAuxpdTxzaZ9-h-imgMKcuXR7H2DRQ6Fa-TD7xjkkj25cx0ksSqL-ILjWw3Kn8rYNGWlMO1A2cLBUxKCMXa_RY_S23vfua2bchGf2cE1dtIDQTdZsnium4nYwnEULV39L9k3w0tsGPLvuIDQcgU_7EXbJe5ytaXOFPQ7gavQO1r/s739/images.png" goup-title="",TV/PAY.PER.VIEW "", BBB 24 
https://em-h.phncdn.com/hls/videos/202003/26/296921351/,221010_0903_1080P_4000K,221010_0903_720P_4000K,221010_0903_480P_2000K,221010_0903_240P_1000K,_296921351.mp4.urlset/index-f2-v1-a1.m3u8?validfrom=1703669032&validto=1703676232&ipa=45.5.202.18&hdl=-1&hash=Ia%2BwRaFeSlZ2T9Yp3wsZ6jOilzY%3D

#EXTM3U
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEjUb0Jxmf2PUO2y-xc3uAwEtVp9pH8yxsTNYPd9SXRq56qyZxZBAp9qy1CcDnE6y253x0Lrru0XvEOpQcohcJSCBYV9AXfS1G_0DMYxFyy8-pqTyNKVe6bGNj3I9DXcgAmzUtbqMh3TjziV9JnA3xko3Gz1jQjlVXTvif3OsKE5ezWPGITvp_PNqnL9MKcu/s300/download.png" group-title="Desenhos 24 Horas",Anime TV
https://stmv1.srvif.com/animetv/animetv/playlist.m3u8

#EXTM3U
#EXTINF:-1 tvg-logo="https://blogger.googleusercontent.com/img/b/R29vZ2xl/AVvXsEhm5Mj3rZrAMBoRaZXC3iIdsdk-BkIyrtrPCKhyhdq4d0kzlkO1mmQOxQF7S6-Cq8Zs_2-iqrj2eZT47TcQNZedQ1pPqaAdS6zcStqP-nlV0fx539bar380IXTauHi4P8Tq6DXitqdn8wyGQOzRidQbFrWCKVABU6UOWyH8czUmcwatrXwiqXBqzbqO2GuG/s3000/Crunchyroll-Logo.wine.png" group-title="Desenhos 24 Horas",Ani TV
https://stream.ichibantv.com:3764/hybrid/play.m3u8

#EXTM3U
 
#EXTINF:-1 tvg-logo="https://telaviva.com.br/wp-content/uploads/2021/01/loading.jpeg" goup-title="",TV/CANAL "", loading 
https://stmv1.srvif.com/loadingtv/loadingtv/playlist.m3u8

**Comment by iBicha** [comment]
These look like an IPTV playlist.
If you're suggesting adding these to Playlet, please note that this is not supported. Playlet is an app to play YouTube content, not any generic IPTV.
