### ISSUE TITLE
Search Screen Bug

### ISSUE THREAD

**Issue by Neipas09** [iBicha/playlet#259]
Can you fix it so that when i go to the SEARCH option at the top,
and i click the --> Right-Arrow to go over to the search box,
that it either 
1. Doesn't auto fill my last search into the search box, thus forcing me to delete whatever is put in there.
2. Goes automatically to an EMPTY search box and not the last search i made.

**Comment by iBicha** [comment]
Thanks for the suggestion. I wouldn't consider this a bug, but UX to be refined.
The purpose of filling in the search is to easily modify the last search. Useful if you're watching some series e.g. you searched for "something ep1" and later you can search for "something ep2" without typing the whole thing again.

But it can be more clicks to go down, clear the search, and start over.
For that, my suggested fix would be to slightly change the layout of the keyboard to make the clear button at the top. This way, if you want to modify existing search, it's easy. But if you want to do a new search, it's one click to clear it.

![keyboard](https://github.com/iBicha/playlet/assets/17722782/8340416c-fd07-47a8-bfc0-d03f36e75992)

**Comment by Neipas09** [comment]
Can you make sure that the default option when you press down from the text box is the clear button?

**Comment by iBicha** [comment]
> For that, my suggested fix would be to slightly change the layout of the keyboard to make the clear button at the top. This way, if you want to modify existing search, it's easy. But if you want to do a new search, it's one click to clear it.

Yup, already done :)

**Comment by iBicha** [comment]
> Can you make sure that the default option when you press down from the text box is the clear button?

Yup, already done :)
