### ISSUE TITLE
Youtube title not display correctly. Does playlet support unicode?

### ISSUE THREAD

**Issue by bachphi** [iBicha/playlet#271]
Youtube title not display correctly. Does the playlet support unicode?

**Comment by iBicha** [comment]
Support for unicode is limited to the languages listed here unfortunately https://www.ccfonts.com/cinecav-styles/

> Albanian, Avar, Basque, Basque, Belarusian, Bosnian, Breton, Bulgarian, Buryat, Catalan, Chamorro, Chichewa, Croatian, Cyrillic, Czech, Danish, Dutch, English, Estonian, Faroese, Finnish, French, Frisian, Galician, German, Greek, Hungarian, Icelandic, Irish, Italian, Kalmyk, Kurdish, Kyrgyz, Latvian, Lithuanian, Macedonian, Malagasy, Maltese, Montenegrin, Norwegian, Ossetian, Polish, Portuguese, Romani, Romanian, Russian, Serbian, Slovak, Slovenian, Spanish, Tajik, Tatar, Turkish, Ukrainian & Welsh.

You can see my comment on solutions here https://github.com/iBicha/playlet/issues/229#issuecomment-1862071240
