### ISSUE TITLE
[Feedback] Playlet

### ISSUE THREAD

**Issue by pvanryn** [iBicha/playlet#30]
### Feedback
I can't figure out how to add my own instance of Invidious. I add my url to the instances table, and then click through it and login, but "Logged in:" remains false. 

Also, I don't understand how to put my url in the box at the top of the table that reads "Login (https://vid.puffyan.us/)" or, how do I put any url in that box other than the default? Do I need to?

Other than that, the app is working great.
#### App Info
```
{
  "id": "dev",
  "version": "0.5.0"
}
```

#### Device Info
```
{
  "display_aspect_ratio": "16x9",
  "display_mode": "720p",
  "display_size": {
    "h": 720,
    "w": 1280
  },
  "display_type": "HDTV",
  "graphics_platform": "opengl",
  "internet_status": true,
  "model": "3900X",
  "model_details": {
    "Manufacturer": "Roku",
    "ModelNumber": "3900X",
    "VendorName": "Roku",
    "VendorUSBName": "Roku"
  },
  "model_display_name": "Roku Express",
  "model_type": "STB",
  "os_version": {
    "build": "4235",
    "major": "11",
    "minor": "5",
    "revision": "0"
  },
  "ui_resolution": {
    "height": 720,
    "name": "HD",
    "width": 1280
  },
  "video_mode": "1080p"
}
```

**Comment by iBicha** [comment]
Hi @pvanryn , thank you for the feedback!

For adding your own instance, as you figured, you just need to add it to the list of instances.

#### Why is there a list?
The list is intended as a fallback. When one instance fails, the next one is used. **This behaviour is not implemented yet, and right now we are simply using the first instance*.

#### How to use your instance specifically
After adding your instance to the list, you just need to make sure the instance you would like to use is at the top of the list.
You can achieve this by:
- Deleting all other instances, leaving just the one you need

OR
- Dragging and dropping your list to the top (the list can be reordered!)

After that, the "Login" button points to the first instance (that's the default)

#### General thoughts around UX
I understand that the UX is not good for now. It is not clear why there's a list, and it is not clear that you can reorder the instances. This will be addressed in a future release.

**Comment by iBicha** [comment]
@pvanryn does this solve your issue?

**Comment by pvanryn** [comment]
I haven't tried to change the server lately, I'll give it another shot and let you know. It is working just fine with the default configuration.

**Comment by iBicha** [comment]
That's great, I'll close this for now then, feel free to open an issue for anything else (or comment on this issue)
