### ISSUE TITLE
[Bug?] Frequent 404 errors

### ISSUE THREAD

**Issue by Wave6677** [iBicha/playlet#309]
Hello, I'm not sure what's happened but recently Ive gotten very frequent HTTP 404 errors while watching videos. It'll be halfway through a video and stop playing it, at which point I have to wait 30 to 90 seconds before it will allow me to play it again. I'm using my own instance so I know the issue is not server downtime. I will post an image of the error the next time I get it (I know it won't be too long before it happens again :P)

**Comment by Wave6677** [comment]
![signal-2024-02-26-06-52-38-715-1](https://github.com/iBicha/playlet/assets/86343914/94a1ea98-b1f3-4d82-ae60-06cf174ee911)
![signal-2024-02-26-06-52-38-715](https://github.com/iBicha/playlet/assets/86343914/5ba24837-f257-4e51-9b2f-c547010e0ba7)

**Comment by Wave6677** [comment]
Two more here in case its helpful in any meaningful capacity
![signal-2024-02-26-06-57-53-551](https://github.com/iBicha/playlet/assets/86343914/1faf54d2-28dd-408f-826b-50135b0a4e26)
![signal-2024-02-26-06-57-53-551-1](https://github.com/iBicha/playlet/assets/86343914/8df0c46a-9b10-42df-9799-e87d4ebc117c)

**Comment by iBicha** [comment]
I have not seen this before on my instance, but what I suggest is
- Use Invidious web interface and see if this is  uniquely happening on Playlet or it is Invidious
- Get the logs from Playlet (`http://ROKU_IP:8888/logs/app_logs.txt`) and inspect them and/or share them with me and I can take a look for anything that can explain what happened
  - If you prefer, you can share the logs with me privately through email (see my profile)
  
From the looks of it, it is just Invidious returning a 404. [This is where that happens](https://github.com/iv-org/invidious/blob/e8a36985aff1a5b33ddf9abea85dd2c23422c2f7/src/invidious/routes/api/v1/videos.cr#L14). If nothing else works, might be worth looking at Invidious logs and see if it is a [video unavailable](https://github.com/iv-org/invidious/blob/e8a36985aff1a5b33ddf9abea85dd2c23422c2f7/src/invidious/videos.cr#L410) issue or something else (I wouldn't also be surprised that YouTube is A/B testing a new change, so only you are seeing this error).

**Comment by iBicha** [comment]
@Wave6677 following up with this issue - does it still happen?
Also I'm guessing this is Google trying to randomly block some connections (I've had another report from a user - similar to this, but not a 404, and the error can appear 10 to 30 minutes into the video)

If you had to guess, would you say the errors started happening roughly after version [[0.20.0] - 2024-02-21](https://github.com/iBicha/playlet/releases/tag/v0.20.0), or before that?

**Comment by Wave6677** [comment]
I feel like it was right around that version, possibly maybe a bit before but my memory is a bit shoddy so I can't recall exactly when it started. It does still happen but as I've been looking into it it does seem like it's an Invidious issue more than a Playlet issue, so if it's helpful to close this issue feel free to, or I can close it, whichever.

**Comment by iBicha** [comment]
Let's keep it open a just a bit further to narrow it down - once we try a couple of things, or we know this is an Invidious fix , then we should close it

**Comment by iBicha** [comment]
In conclusion:
- Setting the `region` on calls to `/api/v1/videos` endpoint (which would lead to fresh video fetch every time) probably did not help much
- Multiple people said the error happens on DASH, but not 720p. DASH (adaptive formats) have more strict checks than the progressive 720p. A possible solution is to throttle the download of the video (to something like 10MB/s) but there isn't an easy way to do that using Roku's Video node.
- As a precaution, the default user agent used for downloading the video is changed.

We will keep an eye on it, but so far, this is all we can do.
