### ISSUE TITLE
Bug: Youtube subscriptions will not load from Invidious

### ISSUE THREAD

**Issue by Yunimori** [iBicha/playlet#347]
I have all of my Youtube subscriptions added to Invidious, and Playlet is logged in to Invidious, but my subscriptions will not show up. My homescreen is just a blank screen unless I add the "Trending" tabs back.

![image](https://github.com/iBicha/playlet/assets/13578499/e0a42a41-12d7-4293-88e1-4811666694be)

**Comment by iBicha** [comment]
Can you share the logs file? You can find a link in the Info tab at the bottom of the page

**Comment by Yunimori** [comment]
I tried it again today and somehow it started working? I was going to give you the logs file, but  now my subscriptions are loaded. I'm not sure if perhaps it was a late-night latency issue or what, but for NOW, everything is working!

**Comment by Yunimori** [comment]
> Can you share the logs file? You can find a link in the Info tab at the bottom of the page

Yes, sure, here you go! 

************* Startup Logs *************
[APP] Loading Playlet lib from https://github.com/iBicha/playlet/releases/latest/download/playlet-lib.zip
[APP] Playlet lib loaded from https://github.com/iBicha/playlet/releases/latest/download/playlet-lib.zip in 7517 ms
*********** End Startup Logs ***********
[INFO][BookmarksService.bs:88] Added bookmark group: Channels
[INFO][BookmarksService.bs:104] Added feedSource bookmark. title: <invalid> id: UCYzPXprvl5Y-Sf0g4vX-m6g
[INFO][ProfilesService.bs:22] Loading profiles from registry...
[INFO][ProfilesService.bs:309] Current profile set to yunimori @ https://invidious.fdn.fr
[INFO][EcpArgs.bs:16] LaunchArgumentsReceived {splashTime: 1818, source: homescreen, instant_on_run_mode: foreground, lastExitOrTerminationReason: EXIT_UNKNOWN}
[INFO][HttpServer.bs:75] listening on 0.0.0.0:8888
[INFO][VideoRowList.bs:290] Loading row content: Subscriptions
[INFO][VideoRowList.bs:290] Loading row content: Trending
[INFO][VideoRowList.bs:290] Loading row content: Trending - Music
[INFO][VideoRowList.bs:290] Loading row content: Trending - Gaming
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/auth/subscriptions ID: 122683417
[INFO][LoungeApi.bs:567] Disconnecting from last lounge
[INFO][HttpClient.bs:332] Sending POST https://www.youtube.com/api/lounge/bc/bind?SID=E10B9C56BC54A958&zx=bqzptozik0zj&capabilities=&id=48ffc122-f879-4aed-a0d6-3a375bd2ce52&theme=cl&t=1&app=lb-v4&VER=8&v=2&device=LOUNGE_SCREEN&RID=1337&name=Playlet%20on%20INSIGNIA%E2%80%A2Roku%20TV%20-%202N00CX483734&mdxVersion=2&loungeIdToken=AGdO5p-7IJ5K4vqvh4VazRHpF_MfMup5aWuMhHHOWQ_hCp4UXGP3sY83kSoEdHXjsTJOJYYt8uiTxUqb5JjgK_f_FzrKmI0yv3hOciyNNB1-SW5oHRUVHkY&gsessionid=r9_C10KsQmuWdMiz5uLRzk0X2rZAcTZ4H9SWRgXnKJY ID: 122683418
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/auth/feed?max_results=20&page=1 ID: 122683419
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/trending?region=US&type=Gaming ID: 122683420
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/trending?region=US&type=Music ID: 122683421
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/trending?region=US ID: 122683422
[INFO][HttpClient.bs:488] Finished ID: 122683421
[INFO][HttpClient.bs:488] Finished ID: 122683420
[INFO][HttpClient.bs:488] Finished ID: 122683422
[INFO][HttpClient.bs:488] Finished ID: 122683417
[INFO][HttpClient.bs:488] Finished ID: 122683419
[INFO][VideoRowList.bs:290] Loading row content: Channels
[INFO][HttpClient.bs:313] Cache hit GET https://invidious.fdn.fr/api/v1/channels/UCYzPXprvl5Y-Sf0g4vX-m6g
[INFO][VideoRowList.bs:290] Loading row content: Subscriptions
[INFO][VideoRowList.bs:290] Loading row content: Trending
[INFO][VideoRowList.bs:290] Loading row content: Trending - Music
[INFO][VideoRowList.bs:290] Loading row content: Trending - Gaming
[INFO][HttpClient.bs:313] Cache hit GET https://invidious.fdn.fr/api/v1/trending?region=US&type=Music
[INFO][HttpClient.bs:313] Cache hit GET https://invidious.fdn.fr/api/v1/trending?region=US&type=Gaming
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/auth/feed?max_results=20&page=1 ID: 122683423
[INFO][HttpClient.bs:313] Cache hit GET https://invidious.fdn.fr/api/v1/trending?region=US
[INFO][HttpClient.bs:488] Finished ID: 122683423
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63723
[INFO][HttpRequest.bs:99] GET '/'
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63723
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63724
[INFO][HttpRequest.bs:99] GET '/index.html'
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63724
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63728
[INFO][HttpRequest.bs:99] GET '/assets/index-aNZLPRxm.js'
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63729
[INFO][HttpRequest.bs:99] GET '/assets/index-DyUt4jcq.css'
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63729
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63728
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63731
[INFO][HttpRequest.bs:99] GET '/api/state'
[INFO][HttpClient.bs:332] Sending HEAD https://github.com/iBicha/playlet/releases/latest ID: 122683424
[INFO][HttpClient.bs:488] Finished ID: 122683424
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63732
[INFO][HttpRequest.bs:99] GET '/api/home-layout'
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63731
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63733
[INFO][HttpRequest.bs:99] GET '/config/default_home_layout.yaml'
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63734
[INFO][HttpRequest.bs:99] GET '/config/invidious_video_api.yaml'
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63732
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63734
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63735
[INFO][HttpRequest.bs:99] GET '/config/preferences.json5'
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63733
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63736
[INFO][HttpRequest.bs:99] GET '/api/preferences'
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63735
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63737
[INFO][HttpRequest.bs:99] GET '/api/search-history'
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63739
[INFO][HttpRequest.bs:99] GET '/api/bookmarks/feeds'
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63736
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63740
[INFO][HttpRequest.bs:99] GET '/locale/en_US/translations.ts'
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63737
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63741
[INFO][HttpRequest.bs:99] GET '/invidious/authenticated-request?feed-source=%7B%22apiType%22%3A%22Invidious%22%2C%22endpoint%22%3A%22auth_feed%22%2C%22id%22%3A%22inv_auth_feed%22%2C%22title%22%3A%22Subscriptions%22%2C%22state%22%3A%7B%22queryParams%22%3A%7B%22page%22%3A1%7D%2C%22paginationType%22%3A%22Pages%22%2C%22page%22%3A1%7D%7D'
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/auth/feed?max_results=20&page=1 ID: 122683425
[INFO][HttpClient.bs:488] Finished ID: 122683425
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63739
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63741
[INFO][HttpConnection.bs:47] recycle
[INFO][HttpConnection.bs:164] receive request peer closed @192.168.1.14:63740
[INFO][VideoRowList.bs:290] Loading row content: Subscriptions
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/auth/feed?max_results=20&page=2 ID: 122683426
[INFO][VideoRowList.bs:290] Loading row content: Trending - Movies
[INFO][HttpClient.bs:332] Sending GET https://invidious.fdn.fr/api/v1/trending?region=US&type=Movies ID: 122683427
[INFO][HttpClient.bs:488] Finished ID: 122683427
[INFO][HttpClient.bs:488] Finished ID: 122683426
[INFO][HttpConnection.bs:58] accepted connection @192.168.1.14:63748
[INFO][HttpRequest.bs:99] GET '/logs/app_logs.txt'

**Comment by iBicha** [comment]
Nothing indicates that anything is wrong. If you open https://invidious.fdn.fr/api/v1/auth/feed?max_results=20&page=1 in the browser, you should be able to see the videos from your feed. Can you confirm?

**Comment by Yunimori** [comment]
Can confirm. I also have just tried switching instances a few times, and finally found one that actually let me view the videos from my feed on the television. It seems the instances I was using just weren't working properly. I'm so sorry, this is the 'wrong' kind of bug!
