### ISSUE TITLE
Failed to load feed

### ISSUE THREAD

**Issue by sarge816** [iBicha/playlet#360]
Just found this promising looking project from a Reddit thread, but once loaded is gives the error in title.

58" Hisense Roku TV, updated to latest firmware:

>Failed to load feed
Reason: SSL certificate problem: unable to get local issuer certificate
StatusCode:  -60

**Comment by iBicha** [comment]
This is very similar to https://github.com/iBicha/playlet/issues/209
It is likely your SSL certificate setup.

Please check the issue. If it does not help share more about your instance (and if public instance are working) and we can debug it

**Comment by sarge816** [comment]
Can you provide more info on what I should be doing for the SSL certificate setup? I am using a standard Roku TV on Comcast internet.  All other apps on the Roku work fine. I looked at the issue you linked and will analyze it further when have more time, thank you for the fast response.  Would love to get this working since the YT normal app is useless.

**Comment by iBicha** [comment]
> Can you provide more info on what I should be doing for the SSL certificate setup? I am using a standard Roku TV on Comcast internet. All other apps on the Roku work fine. I looked at the issue you linked and will analyze it further when have more time, thank you for the fast response. Would love to get this working since the YT normal app is useless.

Are you using your own self-hosted instance? Or a public one? (it's ok if you don't know what this means)

You can also open the web app, go to the info tab, and scroll down to find a link to the logs. Those can help.

**Comment by sarge816** [comment]
This is 100% my fault.  I found the Reddit post, then found the private channel and installed Playlet on my Roku thinking it was a standalone app.  Never came here to see the code, so I never setup any other infrastructure.  Closing this, thank you for the assistance.
