### ISSUE TITLE
Main player in 30 fps and Dev player in 60 fps

### ISSUE THREAD

**Issue by HiRabbi** [iBicha/playlet#370]
Hello, I noticed that the dev video player plays videos at 60 fps while the default one plays videos at 30, I’m not sure if this is a bug or not but it could be a really good feature to have 60 fps on the default video player :]

**Comment by iBicha** [comment]
> Hello, I noticed that the dev video player plays videos at 60 fps while the default one plays videos at 30, I’m not sure if this is a bug or not but it could be a really good feature to have 60 fps on the default video player :]

I believe both should be playing at (a maximum of) 1080p60. I'm testing 60 fps videos, and they both play at 60.
What you're seeing could be related to the settings you have.
The dev player does not take into account the options like "preferred quality" or "proxy videos", and just plays `Auto (DASH)`.

Can you check your settings?

**Comment by HiRabbi** [comment]
Watched a 60 FPS test video on Auto (DASH) and it worked pretty well, thanks!!
