### ISSUE TITLE
More sponsorblock customization options?

### ISSUE THREAD

**Issue by KatttTheFemboi** [iBicha/playlet#377]
Hello, my suggestion is that maybe you should add more ways to customize sponsorblock, such as toggling certain segments like self promo and intro and giving options such as “Do not display notification”, and it’d be cool if you could choose which segments you could skip by hitting a button on the remote :)

**Comment by iBicha** [comment]
Thanks for the suggestion. You're describing what I had in mind as an integration with SponsorBlock.
But I'll close this issue since we already have one for this topic #68
