### ISSUE TITLE
[BUG] “This helps protect our community. Learn more”

### ISSUE THREAD

**Issue by KatttTheFemboi** [iBicha/playlet#400]
Playlet seems to be broken and displays that message

**Comment by iBicha** [comment]
Thanks for reporting, please see https://github.com/iv-org/invidious/issues/4734

**Comment by KatttTheFemboi** [comment]
Sorry didn’t know it was already reported, also I found a server that still works, can I post that?

**Comment by iBicha** [comment]
No worries, it's good to have an issue on this repo as well for visibility. We suspect that this is an incremental rollout where eventually all instances will be affected, even though some are still currently working.

> I found a server that still works, can I post that?

Sure! For anyone facing the same issue (who's not using their own instance) is to try different ones until one works. Use the "Test instance" button in Playlet to test quickly, or test them in the browser.

**Comment by iBicha** [comment]
Update https://github.com/iv-org/invidious/issues/4734#issuecomment-2349782180
> We are aware that Youtube has blocked the trusted-session-generator script and thus the script does not work anymore.
> For the moment there is no solution. We will provide one here once we have found a solution.

**Comment by iBicha** [comment]
https://github.com/iv-org/invidious/issues/4734#issuecomment-2365205990

> Hello,
> 
> Sad news for everyone. YouTube/Google has patched the latest workaround that we had in order to restore the video playback functionality.
> 
> Right now we have no other solutions/fixes. You may be able to get Invidious working on residential IP addresses (like at home) but on datacenter IP addresses Invidious won't work anymore.
> 
> If you are interested to install Invidious at home, we remind you that we have a guide for that here: [https://docs.invidious.io/.](https://docs.invidious.io/installation/).
> 
> This is not the death of this project. We will still try to find new solutions, but this might take time, months probably.
> 
> I have updated the public instance list in order to reflect on the working public instances: https://instances.invidious.io/. Please don't abuse them since the number is really low.
> 
> Feel free to discuss this politely on [Matrix](https://matrix.to/#/#invidious:matrix.org) or [IRC](https://web.libera.chat/?channel=#invidious).

**Comment by allenwalker3** [comment]
Doesn't look good for now. I'm still confused whether this is an IP blacklisting issue or just a general google patch against invidious. I run my own invidious docker instance on my residential IP and no videos play. I tried using a few different VPN IPs and same deal.

**Comment by titan99855** [comment]
The hot fix seems to work pretty well, would it be possible to add an option to use the hot fix for all playback so that playlet can be used without having to use the web remote?

**Comment by iBicha** [comment]
> The hot fix seems to work pretty well, would it be possible to add an option to use the hot fix for all playback so that playlet can be used without having to use the web remote? Just to get by until invidious comes out with a fix.

This is not simple, since https://github.com/LuanRT/YouTube.js was used to implement this temporary fix. Roku does not have a way to run Javascript, so the request is prepared and parsed in the web app, but sent through the Roku device.
Implementing fetching data from Playlet directly is a bigger project.

**Comment by iBicha** [comment]
Right now, the Playlet backend works ok, so I'll close this issue
