### ISSUE TITLE
[SOLUTION] “This helps protect our community. Learn more”

### ISSUE THREAD

**Issue by KatttTheFemboi** [iBicha/playlet#402]
The following servers should still work as of June 9th at 1:20pm EST:

invidious.fdn.fr
inv.tux.pizza (seems to be the best as of June 9th at 1:18pm EST)
invidious.flokinet.to
invidious.privacydev.net (slow but working)
inv.nadeko.net
yt.artemislena.eu
invidious.jing.rocks
invidious.drgns.space
inv.us.projectsegfau.lt
iv.datura.network
invidious.darkness.services
invidious.incogniweb.net
invidious.privacyredirect.com

A lot more than I thought tbh :3

**Comment by iBicha** [comment]
At this point I'll close this ticket since the list in the settings is now mostly up to date, and any blocked instance has been removed. Closing in favor of keeping a single issue tracking this #400
