### ISSUE TITLE
Fox news live feed problem

### ISSUE THREAD

**Issue by istovits** [iBicha/playlet#414]
for the last week or so the juju bot Fox news live feed has a new problem, while playing you can notice words getting clipped like it jumps a  fraction of a second ahead and is most noticeable where there is motion. listen and watch carefully and you should see it.  this happens 1-5 times a minute

**Comment by iBicha** [comment]
Thanks for reporting,  I assume `juju bot Fox news live feed` is https://www.youtube.com/watch?v=C-YHt3Dtc1s
Does this issue occur on any other video/live video?

**Comment by istovits** [comment]
after reinstalling the Roku Youtube app I checked the feed there and saw no hiccups. the problem looks like its on the juju bot end

**Comment by iBicha** [comment]
Thanks for confirming, I will close this issue for now, you can comment further if there are still issues on Playlet side
