### ISSUE TITLE
error playing music

### ISSUE THREAD

**Issue by istovits** [iBicha/playlet#425]
a few days ago when trying to play a song or album I got an error about no valid bitrates.  nothing plays

**Comment by iBicha** [comment]
Please share more information, as this is not enough to investigate
- Which video
- How often / is it consistent
- What is your setup / invidious instance and settings
  - You can find all of this using http://ROKU_DEVICE_IP:8888/api/state
  - You can find this link in the info page of the web app
- Error message dialog and/or logs
  - You can find the logs using http://ROKU_DEVICE_IP:8888/logs/app_logs.txt
  - You can find this link in the info page of the web app

**Comment by iBicha** [comment]
@istovits following up - do you still experience this issue? Can you share more details?

**Comment by iBicha** [comment]
@istovits is this still an issue?

**Comment by iBicha** [comment]
Closing, please comment if this is still an issue
