### ISSUE TITLE
Videos not showing up, black screen

### ISSUE THREAD

**Issue by KatttTheFemboi** [iBicha/playlet#427]
I’m not sure if this is only for me or not but all I hear is the audio of the video, this applies to all videos and it just doesn’t play the video but it still has the audio of the video

**Comment by iBicha** [comment]
Please share more information, as this is not enough to investigate
- How often / is it consistent
- What is your setup / invidious instance and settings
  - You can find all of this using http://ROKU_DEVICE_IP:8888/api/state
  - You can find this link in the info page of the web app
- Error message dialog and/or logs
  - You can find the logs using http://ROKU_DEVICE_IP:8888/logs/app_logs.txt
  - You can find this link in the info page of the web app

Also you might want to restart your device (not just turn it off - restart from System -> Power -> System restart)

**Comment by KatttTheFemboi** [comment]
1. Happens every time even when leaving the app and entering it again

2. TCL Roku 32” TV, invidious.fdn.fr, 720p (no other changed settings)

3. Unable to access the website you put there

4. I’ll try restarting

**Comment by KatttTheFemboi** [comment]
Solved with restarting, hope I didn’t bother, I feel stupid lol
