### ISSUE TITLE
ERROR "Watch on the latest version of YouTube"

### ISSUE THREAD

**Issue by JackHack101** [iBicha/playlet#443]
status code 500

Requestld: 122683453

I want to use this on my TV bc ads and slow apps suck, but I keep getting this error? did I forget to set something up or?

**Comment by iBicha** [comment]
Hello, 
Does the error message say "This helps protect our community. Learn more" somewhere? If so, this is related to #400, you can try to change the invidious instance from the settings.

**Comment by iBicha** [comment]
According to https://github.com/FreeTubeApp/FreeTube/issues/5489 which is also related to using Invidious APIs, both issues are related to https://github.com/iv-org/invidious/issues/4734 so the fix is to use an instance that implements the fix. More instances will be deploying the fix as well.

**Comment by iBicha** [comment]
Right now, the Playlet backend works ok, so I'll close this issue
