### ISSUE TITLE
[Feature Request]  - Include Piped backend and/or yt-local functionality 

### ISSUE THREAD

**Issue by Relaxdaws** [iBicha/playlet#444]
Just a thought :smile:  , but would it be feasible to include Piped backend or yt-local backend? Both of these are similar to invidious. 

https://github.com/TeamPiped/Piped

https://git.sr.ht/~heckyel/yt-local

**Comment by iBicha** [comment]
#75 
For yt-local, I don't see where it supports APIs so Playlet can talk to it. It seems to be it is just web based tool

**Comment by iBicha** [comment]
Yeah unless I'm mistaken, yt-local does not expose a web api that can be used.
For piped, closing in favor of the other issue.
Please correct me if I'm mistaken
Thanks
