### ISSUE TITLE
[BUG] Account deleted maybe?

### ISSUE THREAD

**Issue by KatttTheFemboi** [iBicha/playlet#451]
Hi, I noticed everything disappeared from Playlet, when I tried logging in with the same credentials it registered me instead and now subscriptions and watch history is gone, what happened??

**Comment by iBicha** [comment]
Playlet uses Invidious accounts. Invidious accounts are bound to the server it is created on. For each server in https://api.invidious.io/ when you create an account on a server, it only exists on that server.
If you happen to be using a certain server, and that server is having issues, you might be temporarily unable to access your account. For example, playlet uses a default server https://invidious.fdn.fr if you haven't chosen a specific server, and that server seems to be down for now.

The server owners maintain the database of users on their servers, and usually do their best to protect user data. But sometimes incidents or database corruptions happen. **A good way to protect your profile is to export it from Invidious. Go to settings, `Import/export data`, and choose `Export Invidious data as JSON`. This way you can recreate your profile on another server if needed.**

Also, to know which server your profile is created on, you can see this information in the Profiles screen in the app.
For example my profile in this screenshot is on my local server http://192.168.1.119:8095

![profiles](https://github.com/user-attachments/assets/1834a1d6-9a59-4d5c-9777-671a412fb5b2)

I hope this helps.

**Comment by iBicha** [comment]
@KatttTheFemboi is this still an issue?

**Comment by KatttTheFemboi** [comment]
Yes but I just moved on to a different account, I'll just close it
