### ISSUE TITLE
Support Twitter video media

### ISSUE THREAD

**Issue by xa4hf8** [iBicha/playlet#468]
I just discovered that SpaceX is abandoning YouTube and only broadcasts Starship launches on Twitter now.  Since there is no Twitter media player for Roku, I thought it would be good if the Playlet search function would accept a Twitter handle as input and permit the user to select any video media from the results.

https://www.spacex.com/launches/mission/?missionId=starship-flight-5

https://twitter.com/i/broadcasts/1RDGlyognOgJL

**Comment by iBicha** [comment]
Thanks for the suggestion - unfortunately Playlet is not the right place for this functionality
Although there's no twitter app (maybe there should be one? I don't use twitter) but adding multiple video providers (or making Playlet a general purpose video player) is not realistically feasible, and need to stick to YouTube videos.
For your specific case (long video forms that can be from multiple websites) there are apps that allow you to cast videos from generic websites
