### ISSUE TITLE
503 service unavailable

### ISSUE THREAD

**Issue by istovits** [iBicha/playlet#501]
thats all I get,nothing loads,can't access logs or anything.

**Comment by iBicha** [comment]
What Invidious instance? Please provide as much details as you can, to investigate

**Comment by istovits** [comment]
. 
its working now  and I used nerdvpn. jing.rocks gives me 3 or 4
red Xs when testing that instance and generally does not work.

**Comment by iBicha** [comment]
Glad it works for you.
I can't advise on instances, just looking at https://api.invidious.io/
I personally host an instance on my home server (just for my local network, not exposed to the internet), which keeps things fast.
Invidious has a matrix chat (link in readme https://github.com/iv-org/invidious) perhaps that's a good place to ask about other instances.
