### ISSUE TITLE
Subscribe button broken/buggy

### ISSUE THREAD

**Issue by KatttTheFemboi** [iBicha/playlet#519]
I know it's not supposed to work with the new backend, but even when using invidious the button is kinda weird, and it's either hard to subscribe to a channel or you can't

**Comment by iBicha** [comment]
Thanks for opening the issue. Please provide enough info to investigate (settings, are you logged in, which instance, logs, etc)

> I know it's not supposed to work with the new backend, but even when using invidious the button is kinda weird, and it's either hard to subscribe to a channel or you can't

Try to provide enough context for me to understand what's going on and steps to reproduce the same issue you're facing. Hard to start debugging on "kinda weird"

Thanks!

**Comment by KatttTheFemboi** [comment]
Settings: Autoplay Off, Preffered quality 1080p, Backend Playlet, Instance Playlet Built In, Proxy only if needed, Sponsorblock enabled, sponsorblock notifications enabled, search history enabled, queue notifications enabled

Logged in: yes

Instance: usually inv.nadeko.net

Logs: "Cannot GET /logs/app_logs_previous.txt
generated by Playlet on Mon, 23 DEC 2024 23:21:23 GMT"

Hardware: TCL 32" Roku TV

Info: I tested it when I could back then and subscribing wouldn't work or would act weird (click the button then it wouldn't work, click it a few more times then it would work), but now I can't test it again since all instances have api's disabled :(

**Comment by iBicha** [comment]
Thanks for the info. I was able to reproduce the issue by looking at the logs
> Logs: "Cannot GET /logs/app_logs_previous.txt

Yeah, sometimes logs get deleted (Roku deletes them when the cache gets full)

I was able to reproduce the issue - this is an instance specific error.
The maintainer of inv.nadeko.net made modifications to his instance(s) so the API access is restricted.

```
[18:47:13.185][ERROR]InvidiousSubscriptionsTask.InvidiousSubscriptionsTask(20) Error getting subscriptions: Reason:Forbidden
StatusCode: 403
RequestId: 122683393
Body: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>
```
And
```
[18:50:34.074][ERROR]SubscribeTask.SubscribeTask(23) Failed to subscribe/unsubscribe to channel: Reason:Forbidden
StatusCode: 403
RequestId: 122683412
Body: <html>
<head><title>403 Forbidden</title></head>
<body>
<center><h1>403 Forbidden</h1></center>
<hr><center>openresty</center>
</body>
</html>
```

Even though subscriptions work normally on other instances (code for subscriptions didn't change in a long time)

So Playlet can't do much here, if the instance doesn't want to provide API access (although misleading https://api.invidious.io) - can't get subscription list, and can't toggle subscriptions on/off.

The maintainer seems to dislike API usage in general it seems https://git.nadeko.net/Fijxu/invidious/wiki/Important-information

**Comment by iBicha** [comment]
What you can do is: subscribe to channels on the browser, add playlists to your profile, and then subs, playlists and watch history should be accessible from Playlet.

**Comment by KatttTheFemboi** [comment]
Oh ok, thanks!!
