### ISSUE TITLE
[Roku OS < 10.0 ] Dialog Crash

### ISSUE THREAD

**Issue by iBicha** [iBicha/playlet#55]
From BrightScript Crash Logs with Stacktraces
<img width="1046" alt="Screen Shot 2023-03-04 at 8 48 43 PM" src="https://user-images.githubusercontent.com/17722782/222937214-16953755-0f1f-4b56-b9ee-c353749cb3f1.png">

**Comment by iBicha** [comment]
Looks like an issue with usage of [StandardMessageDialog](https://developer.roku.com/en-ca/docs/references/scenegraph/standard-dialog-framework-nodes/standard-message-dialog.md) which is _Available since Roku OS 10.0_ while the crash is happening on 9.20

**Comment by cewert** [comment]
I believe the solution to your crash is to change the `Minimum firmware` dropdown under `Package upload` next time you publish your app on roku.com. This will prevent the crash by preventing the device from downloading your app in the first place on the roku store. They should still be able to sideload the app but I'm not positive.


![roku-min-version](https://github.com/iBicha/playlet/assets/16514652/b59bff65-4406-4752-a3fc-173736d6aefc)

**Comment by iBicha** [comment]
Thanks for the suggestion @cewert 
Yeah I was considering either setting the minimum version or not using the dialog 
But I think your solution is probably simplest. Since most Rokus auto-update, I believe the number of people this affects is low. But I don't have data to back that up

**Comment by cewert** [comment]
Yea not using the dialog totally works too, sorry. I don't know your code base I was just browsing 😄 I just thought you might not know about the setting. We actually need to update ours as well so it caught my eye.

According to the docs [here](https://developer.roku.com/en-gb/docs/specs/hardware.md#legacy-models) if your user has v9.2 I believe he should be able to upgrade to v11. The legacy models `Latest Roku OS version` go from `3.1` to `9.1` to `11` to `11.5`

**Comment by iBicha** [comment]
> Yea not using the dialog totally works too, sorry. I don't know your code base I was just browsing 😄 I just thought you might not know about the setting. We actually need to update ours as well so it caught my eye.
> 
> According to the docs [here](https://developer.roku.com/en-gb/docs/specs/hardware.md#legacy-models) if your user has v9.2 I believe he should be able to upgrade to v11. The legacy models `Latest Roku OS version` go from `3.1` to `9.1` to `11` to `11.5`

You are right, I will just bump to a minimum of 10.0 on next publish

**Comment by iBicha** [comment]
App published with minimum os 10.0
