### ISSUE TITLE
No subscriptions

### ISSUE THREAD

**Issue by WizardOfWor1969** [iBicha/playlet#77]
PLaylet says I am logged in , but no subscriptions show up on my Home screen.

I am using a Roku box and my server is https://vid.puffyan.us/

**Comment by WizardOfWor1969** [comment]
Played a bit more with it. I signed out from Playlet settings on my phone. Then I clicked sign in , then I was asked to Authorize Token and I get Invalid Signature from Invidious.

**Comment by iBicha** [comment]
Hi @WizardOfWor1969 thanks for reporting the issue.
The first part where the subscriptions are no visible but you are logged in, it usually means the server did not consider your access token valid. Combined with the "Invalid Signature" error, both are symptoms of misconfigured Invidious instance.

It is likely a case of missing `hmac_key` in the config (documentation [here](https://docs.invidious.io/installation/#post-install-configuration))

#### What does that mean?
It means that when an administrator does not configure the `hmac_key`, it gets randomly generated. But it also gets regenerated every time the Invidious instance is restarted. When that happens, it might cause the valid token that Playlet uses to become invalid. It also causes the "Invalid Signature" on login, and you might need to try a few times before it works.

#### How to fix it
I proposed a fix to the Invidious team https://github.com/iv-org/invidious/issues/3540 to make the Instance remember this randomly generated key. They said this is down to instance maintainers to configure Invidious properly.
You might need to reach out to your instance maintainer and link them to the documentation about `hmac_key`

Same issue as #65

**Comment by iBicha** [comment]
Most maintainers has been informed of this needed config in https://github.com/iv-org/documentation/issues
So if you search here https://github.com/iv-org/documentation/issues?q=HMAC_KEY
You can find some maintainers confirming they did this
For example https://github.com/iv-org/documentation/issues/314#issuecomment-1374280839

**Comment by WizardOfWor1969** [comment]
Thank you.
